# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a35tcpg236-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/subir/Desktop/VHDL Projects/carry_lookahead/carry_lookahead.cache/wt} [current_project]
set_property parent.project_path {C:/Users/subir/Desktop/VHDL Projects/carry_lookahead/carry_lookahead.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib {{C:/Users/subir/Desktop/VHDL Projects/carry_lookahead/carry_lookahead.srcs/sources_1/new/carry_lookahead.vhd}}
catch { write_hwdef -file carry_lookahead.hwdef }
synth_design -top carry_lookahead -part xc7a35tcpg236-1
write_checkpoint -noxdef carry_lookahead.dcp
catch { report_utilization -file carry_lookahead_utilization_synth.rpt -pb carry_lookahead_utilization_synth.pb }
