# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a35tcpg236-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/subir/Desktop/VHDL Projects/Mux/Mux.cache/wt} [current_project]
set_property parent.project_path {C:/Users/subir/Desktop/VHDL Projects/Mux/Mux.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib {{C:/Users/subir/Desktop/VHDL Projects/Mux/Mux.srcs/sources_1/new/Mux.vhd}}
catch { write_hwdef -file Mux.hwdef }
synth_design -top Mux -part xc7a35tcpg236-1
write_checkpoint -noxdef Mux.dcp
catch { report_utilization -file Mux_utilization_synth.rpt -pb Mux_utilization_synth.pb }
